<a href="https://colab.research.google.com/github/PrithuVerma/Basic_Projects/blob/main/Tensors_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
    print('GPU is available')
    print(torch.cuda.get_device_name())
else:
    print('No GPU in sight, using CPU')

No GPU in sight, using CPU


# **Creating** **Tensors**

In [ ]:
a = torch.empty(3,3)
print(a)

tensor([[ 1.0501e-37,  4.4519e-41,  1.0501e-37],
        [ 4.4519e-41,  1.5080e-38,  0.0000e+00],
        [-1.8388e+30,  4.4516e-41,  1.3595e-38]])


In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(4,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
torch.rand(2,3) #Random values between 0-1

tensor([[0.3129, 0.2784, 0.9400],
        [0.1325, 0.2221, 0.2345]])

In [ ]:
torch.manual_seed(50)
torch.rand(2,3)

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442]])

In [ ]:
torch.manual_seed(50) #manual_seed is used to counter randomness of torch.rand function
torch.rand(2,3)

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442]])

In [ ]:
torch.tensor([[4,5,6],[1,2,3]])

tensor([[4, 5, 6],
        [1, 2, 3]])

In [ ]:
print('Using arange : ',torch.arange(0,10))
print('Using Linspace : ',torch.linspace(0,10,5)) #returns an evenly spaced  tensor from 0-10 of space 5
print('Using Eye (Indetity Matrix) : ',torch.eye(4))
print('Using Full : ',torch.full((3,3),4)) # returns tensor of 3X3 with every value 4

Using arange :  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Using Linspace :  tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
Using Eye (Indetity Matrix) :  tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
Using Full :  tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])


# **Tensor Shape**

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x) # creates a tensor of same size/shape but of different values

tensor([[    137989264469392,     137989264469392,                   0],
        [                  0,     137984414318592, 7307199746910528123]])

In [ ]:
print(torch.zeros_like(x))
print(torch.ones_like(x))

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])


In [ ]:
torch.rand_like(x) # This will throw an error becuase _like() returns integer value but rand() gives float values between 0-1

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

# **Tensor Datatypes**

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0,4.0],dtype=torch.int32)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
torch.rand_like(x,dtype= torch.float32) #fixing the issue of rand_like()

tensor([[0.0047, 0.5807, 0.5516],
        [0.1511, 0.5054, 0.3276]])

# **Mathematical Operation**

In [ ]:
tsr = torch.rand(3,3)
val = 2
print(tsr + val)
print(tsr - val)
print(tsr * val)
print(tsr / val)

tensor([[2.6981, 2.5052, 2.8755],
        [2.9573, 2.4254, 2.4930],
        [2.0396, 2.0162, 2.8851]])
tensor([[-1.3019, -1.4948, -1.1245],
        [-1.0427, -1.5746, -1.5070],
        [-1.9604, -1.9838, -1.1149]])
tensor([[1.3962, 1.0103, 1.7510],
        [1.9145, 0.8508, 0.9860],
        [0.0792, 0.0325, 1.7703]])
tensor([[0.3490, 0.2526, 0.4378],
        [0.4786, 0.2127, 0.2465],
        [0.0198, 0.0081, 0.4426]])


tensor([[0.3061, 0.3083],
        [0.7605, 0.7904]])
tensor([[0.4321, 0.9726],
        [0.1641, 0.1379]])


tensor([[0.1322, 0.2999],
        [0.1248, 0.1090]])

In [ ]:
r = torch.randint(size=(3,3),low=1,high=20,dtype=torch.float32)
print(r)

torch.sum(r)
print(torch.sum(r,0),'\n') #column sum
print(torch.sum(r,1),'\n') #row sum

print(torch.mean(r),'\n') #mean does not work for int data type
print(torch.mean(r,0),'\n') #column mean
print(torch.mean(r,1),'\n') #row mean

print(torch.median(r),'\n') #median does not work for int data type
print(torch.median(r,0),'\n') #column median
print(torch.median(r,1),'\n') #row median

print(torch.prod(r),'\n\t')
print(torch.std(r),'\n')
print(torch.var(r),'\n')

print(torch.argmin(r),'\n')#tells the position of minimun elements in a tensor
print(torch.argmax(r),'\n')#tells the position of maximun elements in a tensor

tensor([[14., 15.,  8.],
        [ 7.,  5.,  9.],
        [ 2., 14., 19.]])
tensor([23., 34., 36.]) 

tensor([37., 21., 35.]) 

tensor(10.3333) 

tensor([ 7.6667, 11.3333, 12.0000]) 

tensor([12.3333,  7.0000, 11.6667]) 

tensor(9.) 

torch.return_types.median(
values=tensor([ 7., 14.,  9.]),
indices=tensor([1, 2, 1])) 

torch.return_types.median(
values=tensor([14.,  7., 14.]),
indices=tensor([0, 0, 1])) 

tensor(2.8153e+08) 
	
tensor(5.4772) 

tensor(30.) 

tensor(6) 

tensor(8) 



# **Matrix Operations**

In [ ]:
f = torch.randint(size=(2,2),low=1,high=10,dtype=torch.float32)
g = torch.randint(size=(2,2),low=1,high=10,dtype=torch.float32)

print(f)
print(g)

#matrix multiplication

torch.matmul(f,g)

tensor([[3., 6.],
        [1., 6.]])
tensor([[6., 2.],
        [9., 9.]])


tensor([[72., 60.],
        [60., 56.]])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

torch.dot(vector1,vector2)


tensor(11)

In [ ]:
h = torch.tensor([[3,6,4],[1,6,7]])
print(torch.transpose(h,0,1))
j = torch.tensor([[10.,4.],[12.,7.]])
print(torch.det(j))

tensor([[3, 1],
        [6, 6],
        [4, 7]])
tensor(22.0000)


# **Trignometric Operations**

In [ ]:
n = torch.randint(size=(2,3),low=1,high=10,dtype=torch.float32)
print(n,'\n')
print(torch.log(n),'\n')
print(torch.exp(n),'\n')
print(torch.sin(n),'\n')
print(torch.cos(n),'\n')
print(torch.tan(n),'\n')

tensor([[5., 3., 4.],
        [1., 9., 3.]]) 

tensor([[1.6094, 1.0986, 1.3863],
        [0.0000, 2.1972, 1.0986]]) 

tensor([[1.4841e+02, 2.0086e+01, 5.4598e+01],
        [2.7183e+00, 8.1031e+03, 2.0086e+01]]) 

tensor([[-0.9589,  0.1411, -0.7568],
        [ 0.8415,  0.4121,  0.1411]]) 

tensor([[ 0.2837, -0.9900, -0.6536],
        [ 0.5403, -0.9111, -0.9900]]) 

tensor([[-3.3805, -0.1425,  1.1578],
        [ 1.5574, -0.4523, -0.1425]]) 



# **Special Operations**

In [ ]:
z = torch.randint(size=(2,3),low=1,high = 10, dtype= torch.float32)
print(torch.sigmoid(z),'\n') #sigmoid transforms a continuous real number into a range of (0, 1)

print(torch.softmax(z,dim=0),'\n') #softmax normalize the values of a given tensor into probabilities

print(torch.relu(z),'\n') #replaces all the negative values with 0 and all the non-negative left unchanged

tensor([[0.9997, 0.9526, 0.9820],
        [0.9999, 0.9526, 0.9820]]) 

tensor([[0.2689, 0.5000, 0.5000],
        [0.7311, 0.5000, 0.5000]]) 

tensor([[8., 3., 4.],
        [9., 3., 4.]]) 



# **Inplace Operation**
It is used to store changes into a tensor itself without creating a new one, any operation having **"_"** at the end represent Inplace Op.

In [ ]:
a = torch.randint(size=(2,3),low=1,high=10,dtype=torch.float32)
b = torch.randint(size=(2,3),low=1,high=10,dtype=torch.float32)
print(a)
print(b)

a.add_(b)

tensor([[7., 4., 2.],
        [2., 9., 9.]])
tensor([[2., 5., 8.],
        [7., 3., 7.]])


tensor([[ 9.,  9., 10.],
        [ 9., 12., 16.]])

# **Copying a Tensor**
This is different from basic python copying operation (assigmnet "= " operand) it creates a copy that isn't affected when the original is edited, it creates a new memory location rather than pointing at the same one

In [ ]:
c = torch.rand((2,3))
d = torch.rand((2,3))

d = c.clone()
print(d)

# **Reshaping**

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2,2,2,2) # the product of orginal and reshaped must be same

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.6155, 0.8488, 0.2979, 0.9971],
         [0.6866, 0.5765, 0.2186, 0.8063],
         [0.5781, 0.5397, 0.1803, 0.2823]],

        [[0.0232, 0.9431, 0.0174, 0.6644],
         [0.8501, 0.7945, 0.1565, 0.8589],
         [0.2212, 0.0744, 0.3737, 0.8789]]])

In [ ]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
b.permute(2,0,1)

tensor([[[0.6155, 0.6866, 0.5781],
         [0.0232, 0.8501, 0.2212]],

        [[0.8488, 0.5765, 0.5397],
         [0.9431, 0.7945, 0.0744]],

        [[0.2979, 0.2186, 0.1803],
         [0.0174, 0.1565, 0.3737]],

        [[0.9971, 0.8063, 0.2823],
         [0.6644, 0.8589, 0.8789]]])

In [ ]:
c = torch.rand(226,226,3)
c.unsqueeze(0).shape #adds a new dimesion to the given index value

torch.Size([1, 226, 226, 3])

In [ ]:
d = torch.rand(1,20)
d.squeeze(0).shape #removes a dimension from a tensor's given index

torch.Size([20])

# **Converting NumPy Array to Tensor and Vice Versa**

In [ ]:
import numpy as np

In [ ]:
g = torch.tensor([1,2,3,4])
g

tensor([1, 2, 3, 4])

In [ ]:
h = g.numpy()
h

array([1, 2, 3, 4])

In [ ]:
i = np.array([1,2,3,4])
i

array([1, 2, 3, 4])

In [ ]:
k = torch.from_numpy(i)
k

tensor([1, 2, 3, 4])